admin: 'iamalazyrat@gmail.com'

site:
  name: 'app'
  domain: 'app.com'

nav:
  items: [
    {cname: '设置', controller: 'settings', link: '/cpanel/settings'}, 
    {cname: '页面', controller: 'pages', link: '/cpanel/pages'}, 
    {cname: '分类', controller: 'sections', link: '/cpanel/sections'}, 
    {cname: '节点', controller: 'nodes', link: '/cpanel/nodes'}, 
    {cname: '物品', controller: 'things', link: '/cpanel/things'}, 
    {cname: '附件', controller: 'attachments', link: '/cpanel/attachments'}, 
    {cname: '标签', controller: 'tags', link: '/cpanel/tags'}, 
    {cname: '商城', controller: 'malls', link: '/cpanel/malls'}, 
    {cname: '广告', controller: 'ads', link: '/cpanel/ads'}, 
    {cname: '活动', controller: 'promotions', link: '/cpanel/promotions'}, 
  ]

fnav:
  items: [
  ]
